### ISSUE TITLE
git repo is really big

### ISSUE THREAD

**Issue by cbischoff** [jmert/html-figure-pager#1]
I just cloned this and it was a ~500 MB download. I think this is because you committed all the spherical harmonic images for the demo site? Any way to remove this from the git history to slim down the repo? In the meantime, I will just copy the .css and .js files and delete the rest.

**Comment by jmert** [comment]
Yeah, I'm making use of Github Pages to serve the demo site, so it had to be a branch in the repo.

You can do a shallow-clone of the history to get something much lighter.
```bash
git clone --depth 1 https://github.com/jmert/html-figure-pager
```
![image](https://user-images.githubusercontent.com/2965436/229879843-8d70adc3-175b-4b10-8dcf-857d80041e06.png)

If all you need is the files, that should be enough.

"Unshallowing" the clone also seems to avoid actually obtaining the unrelated `gh-pages` branch, so you can also access a lightweight copy of the entire (non-website) history after the shallow clone above with:
```bash
git pull --unshallow
```
![image](https://user-images.githubusercontent.com/2965436/229880833-d1d4b3f0-1b41-42ef-8a8e-2c9d4b9e775b.png)

**Comment by cbischoff** [comment]
Great. Thank you!

**Comment by jmert** [comment]
I'll add this to the README in the next day or so.
